// Generated by scripts/gen-classic-app.mts from src/app/api/reference-check/route.ts — do not edit.
export const runtime = 'nodejs';
export * from 'prompt-studio-core/src/app/api/reference-check/route';
