// Generated by scripts/gen-classic-app.mts from src/studio-app/plugins/nsfw-generator/page.tsx — do not edit.
export * from 'prompt-studio-core/src/studio-app/plugins/nsfw-generator/page';
export { default } from 'prompt-studio-core/src/studio-app/plugins/nsfw-generator/page';
