// Generated by scripts/gen-classic-app.mts from src/app/video/page.tsx — do not edit.
export * from 'prompt-studio-core/src/app/video/page';
export { default } from 'prompt-studio-core/src/app/video/page';
