// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/history/workflow/route.ts — do not edit.
export const runtime = 'nodejs';
export * from 'prompt-studio-core/src/app/api/comfyui/history/workflow/route';
