// Generated by scripts/gen-classic-app.mts from src/app/api/shared-projects/route.ts — do not edit.
export const runtime = 'nodejs';
export * from 'prompt-studio-core/src/app/api/shared-projects/route';
