// Generated by scripts/gen-classic-app.mts from src/app/gallery/loading.tsx — do not edit.
export * from 'prompt-studio-core/src/app/gallery/loading';
export { default } from 'prompt-studio-core/src/app/gallery/loading';
