// Generated by scripts/gen-classic-app.mts from src/app/api/fal/media/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 120;
export * from 'prompt-studio-core/src/app/api/fal/media/route';
