// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/model-files/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 120;
export * from 'prompt-studio-core/src/app/api/comfyui/model-files/route';
