// Generated by scripts/gen-classic-app.mts from src/app/apple-icon.tsx — do not edit.
export const size = { width: 180, height: 180 };
export const contentType = 'image/png';
export * from 'prompt-studio-core/src/app/apple-icon';
export { default } from 'prompt-studio-core/src/app/apple-icon';
