// Generated by scripts/gen-classic-app.mts from src/app/icon.tsx — do not edit.
export const size = { width: 32, height: 32 };
export const contentType = 'image/png';
export * from 'prompt-studio-core/src/app/icon';
export { default } from 'prompt-studio-core/src/app/icon';
