// Generated by scripts/gen-classic-app.mts from src/app/opengraph-image.tsx — do not edit.
export const alt = 'Castcut';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';
export * from 'prompt-studio-core/src/app/opengraph-image';
export { default } from 'prompt-studio-core/src/app/opengraph-image';
