// Generated by scripts/gen-classic-app.mts from src/app/api/isolate-subject/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 180;
export * from 'prompt-studio-core/src/app/api/isolate-subject/route';
