// Generated by scripts/gen-classic-app.mts from src/app/api/clip-voice/route.ts — do not edit.
export const runtime = 'nodejs';
export const maxDuration = 280;
export * from 'prompt-studio-core/src/app/api/clip-voice/route';
