// Generated by scripts/gen-classic-app.mts from src/studio-app/logo/page.tsx — do not edit.
export * from 'prompt-studio-core/src/studio-app/logo/page';
export { default } from 'prompt-studio-core/src/studio-app/logo/page';
