// Generated by scripts/gen-classic-app.mts from src/app/api/settings/queue-export/route.ts — do not edit.
export const runtime = 'nodejs';
export * from 'prompt-studio-core/src/app/api/settings/queue-export/route';
