// Generated by scripts/gen-classic-app.mts from src/app/api/comfyui/live/route.ts — do not edit.
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 600;
export * from 'prompt-studio-core/src/app/api/comfyui/live/route';
