// Generated by scripts/gen-classic-app.mts from src/proxy.ts — do not edit.
export const config = {
  matcher: [
    '/api/:path*',
    '/((?!_next/static|_next/image|favicon.ico|manifest.json|manifest-mobile.json|icons|sw.js|sw-gallery.js|wildcards|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
import type { NextRequest } from 'next/server';
import { proxy as sharedProxy } from 'prompt-studio-core/src/proxy';
export function proxy(request: NextRequest) {
  return sharedProxy(request);
}
