// Generated by scripts/gen-classic-app.mts from src/app/api/collab/route.ts — do not edit.
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export * from 'prompt-studio-core/src/app/api/collab/route';
