// Generated by scripts/gen-classic-app.mts from src/app/settings/page.tsx — do not edit.
export * from 'prompt-studio-core/src/app/settings/page';
export { default } from 'prompt-studio-core/src/app/settings/page';
